### ISSUE TITLE
Timer.jsx 수정 요청

### ISSUE THREAD

**Issue by nowjiin** [nowjiin/livfit-fe#3]
play/squart , play/stretch, play/lunge 에 포함되어있는
Timer.jsx component에서
00:00 에서 시간이 지날 경우
-00:01, -00:02로 되는 오류

**Comment by bigone-77** [comment]
아직 push 하지 않아서 늦어도 23일 화요일까지는 올려놓도록 하겠습니다 !

**Comment by bigone-77** [comment]
타이머 버그 수정 완료 및 paused 추가
